name: Deploy to Server

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd shohibul-quran-bot/
            git pull origin main
            sudo docker compose build
            sudo docker compose up -d
